### PR TITLE
createShipment: packetId -> packetIds

### PR DESCRIPTION
**Pull request by radimvaculik**

### CODE REVIEW

**Comment by radimvaculik** [comment]
@Salamek Could you check it, please? 🙏

**Comment by Salamek** [comment]
@radimvaculik looks ok and looks like it matches the DOC, is this tested by you and working fine?

**Comment by radimvaculik** [comment]
Tested 👍 Could you also tag it as new version, please? Thx.

**Comment by Salamek** [comment]
Done!

**Pull request merged**
