### PR TITLE
PacketAttributes: Add smart validations.

### PR DESCRIPTION
**Pull request by janbarasek**
Validations added to methods + call constructor params by methods for use validation rules.

### CODE REVIEW

**Comment by janbarasek** [comment]
ping @Salamek

**Comment by Salamek** [comment]
@janbarasek would be nice to force users to use `int` for zip in the future so we can get rid of that casting in `setZip` and `getZip`, so i would like to see something like:
```php
trigger_error('Passing $zip as a string into  ' . __METHOD__ . ' is deprecated please use int instead. This will be enforced in next minor version', E_USER_DEPRECATED);
```
To notify user of this library that they should pass int not string in `setZip` when string is detected and `getZip` should return passed type (so remove string return type)?

What do you think?

**Comment by janbarasek** [comment]
@Salamek I think it's good to be benevolent for more types of inputs, because string formatting can be challenging (from different external systems). PHP 8 brings union types that allow this.

**Comment by Salamek** [comment]
@janbarasek from my experience in PHP world, i seen many apps that had weird bugs when it's creators were benevolent in variable types (loss of precision in AUTOMATIC type casting and such a stuff, usually PHP5 code) and in this case i don't see any reason for allowing `int` and `string` at the same time... 

and well... if we are doing that we can just keep string type... that is basically same as using Union[int, string] but in this case we are adding two "hidden" casts into the library code.

And finally when i'm using some model like class with getter/setter interface, i expect this to be `true`:

```php
$zip = 123456;
$p = new Salamek\Zasilkovna\Model\PacketAttributes(
    zip: $zip
);

print_r($p->getZip() === $zip);
```

We don't need to care from where the ZIP code is provided to this class, that is library integrator responsibility to preprocess and provide correct data, so lets say they want to pass data from database where zip is in plain text directly from order form without any validation/formatting... so it is library integrator responsibility to do ~this:

```php

$zip = (int)preg_replace('/\D/', '', $order->getZip());

$p = new Salamek\Zasilkovna\Model\PacketAttributes(
    zip: $zip
); // Zip is defined as int
```

BUT if we look into the official WSDL file https://www.zasilkovna.cz/api/soap.wsdl, PacketAttributes.zip is defined as `xsd:string` so i think we should comply with that -> keep ZIP as string and add \s*[0-9]{3} ?[0-9]{2}\s* as validation in `setZip`

**Comment by janbarasek** [comment]
@Salamek Thank you for the extensive answer.

We keep the return type for `getZip()` as a string or null all the time.

To be as strict as possible in the internal implementation, I allowed Zip to be accepted as an int or string in the constructor, but a particular setter accepts only one of the types, so it never breaks, and when the user enters something invalid, it gets an exception or type error.

We store the zip internally as an int, but on the output it is formatted as a string in the format you specified.

So what to do like this?

----

**Code snippet**

```php
public function getZip(): ?string
{
	if ($this->zip === null) {
		return null;
	}
	return (string) preg_replace('/^(\d{3})(\d{2})$/', '$1 $2', $this->zip);
}

public function setZip(?int $zip): void
{
	if ($zip === null) {
		$this->zip = null;
		return;
	}
	if ($zip < 10000) {
		throw new \InvalidArgumentException('Zip "' . $zip . '" is too small.');
	}
	if ($zip > 99999) {
		throw new \InvalidArgumentException('Zip "' . $zip . '" is too big.');
	}
	$this->zip = $zip;
}

public function setZipString(string $zip): void
{
	$this->setZip((int) preg_replace('/\D/', '', $zip));
}
```

**Pull request closed without merging**
