### PR TITLE
Fixing PacketAttributesFault

### PR DESCRIPTION
**Pull request by MikyWoW**
Errors needs to be handled differently when there is one or many of them.

### CODE REVIEW

**Comment by thorewi** [comment]
@MikyWoW why true == false please? it's quite hard to read the condition and understand it correctly. It would be nice to have a comment to such imho "complicated" condition... Thank you.

**Comment by MikyWoW** [comment]
Oh sorry, my bad. For some reason i wanted to use ?? instead of isset() and make this mess in process. That's why is code review good thing. You can replace that line with just simple:
```php
if(isset($fails['name'])) {
```

**Comment by thorewi** [comment]
Can you create a new PR please?

**Comment by MikyWoW** [comment]
#21

**Pull request merged**
